
import { createClient } from '@supabase/supabase-js';
import { Team, TeamStatus, UserRole, UserSession, ProblemStatement, Evaluation } from '../types';
import { supabase } from './supabaseService'; // Use Singleton
export { supabase };

export let isDemoMode = false;

// We assume supabaseService handles the real connection.
// If it fails, mockSupabase logic might need adjustment, but for now we unify.

// --- Problem Statements (Updated from PDF) ---
export const mockProblemStatements: ProblemStatement[] = [
  {
    id: 'PS-01',
    title: 'Silent Session Expiry Causing Unauthorized Actions in Web Portals',
    domain: 'Web Development',
    difficulty: 'Beginner',
    realWorldContext: 'Users of internal web portals (HR systems, admin dashboards, academic or municipal portals) frequently remain logged in for long periods while performing intermittent tasks. These portals are accessed daily by staff handling sensitive but routine operations. In practice, user sessions expire due to inactivity, backend restarts, or policy-enforced timeouts. This happens multiple times per day in real organizations, especially during long form submissions or multi-step workflows.',
    coreProblem: 'Web applications often fail to clearly and consistently handle expired user sessions on the client side. As a result, users continue interacting with the interface after session expiry, unknowingly submitting actions that are rejected, misapplied, or executed under an invalid or unintended authentication state. Existing implementations rely on ad-hoc checks, inconsistent HTTP responses, or full-page reloads, which do not reliably prevent user confusion or unintended actions.',
    constraints: [
      'Session expiration timing is controlled server-side and cannot be predicted precisely by the client.',
      'Network latency and intermittent connectivity may delay or reorder responses.',
      'The client cannot assume uniform API error formats across endpoints.',
      'Users may have multiple tabs of the same application open simultaneously.',
      'Page reloads may cause loss of unsaved user input, which is unacceptable for long forms.'
    ],
    failureScenarios: [
      'Delayed Failure Feedback: A user submits a form after session expiry. The server rejects the request, but the UI shows a generic error. The user retries multiple times, losing work and trust.',
      'Partial Action Execution: Some requests succeed before expiry while later ones fail. The system ends in an inconsistent state from the user’s perspective.',
      'Cross-Tab Confusion: A session expires in one tab due to inactivity. Another tab appears functional but silently fails on submission.'
    ],
    evaluationCriteria: [
      'The system must reliably detect expired or invalid sessions during active use.',
      'User-facing behaviour must be consistent across different actions and views.',
      'Loss of user input due to session expiry must be demonstrably minimized.',
      'Incorrect assumptions about session validity or backend behaviour will be penalized.'
    ],
    deliverables: [
      'A minimal working web interface demonstrating the failure and its handling.',
      'Clear evidence (logs or UI behaviour) showing how expired sessions are detected.',
      'A live demonstration of at least one failure scenario being handled correctly.',
      'A short written explanation of remaining edge cases and limitations.'
    ]
  },
  {
    id: 'PS-02',
    title: 'Incorrect Aggregated Metrics Due to Late-Arriving Event Data',
    domain: 'Data & Analytics',
    difficulty: 'Beginner',
    realWorldContext: 'Operational dashboards are widely used by teams monitoring daily activity such as transactions processed, requests served, or tasks completed. These dashboards consume event data generated by distributed systems where events are produced continuously and collected asynchronously. In real environments, events frequently arrive late due to network delays, retries, batching, or temporary service outages. This occurs daily in systems processing moderate to high volumes of activity.',
    coreProblem: 'Simple aggregation logic assumes that all relevant events for a time window arrive within that window. When events arrive late, aggregated metrics such as daily counts or totals become incorrect and silently diverge from reality. Existing implementations often overwrite or ignore late data, making it impossible to produce reliable historical metrics without manual correction.',
    constraints: [
      'Event timestamps cannot be trusted to arrive in chronological order.',
      'Some events may arrive minutes or hours after their actual occurrence.',
      'The system cannot reprocess the entire dataset on every update due to time limits.',
      'Duplicate events may exist and cannot be assumed absent.',
      'The definition of a “day” or reporting window is fixed and cannot be shifted.'
    ],
    failureScenarios: [
      'Underreported Metrics: Late events arrive after a report is generated. Daily totals remain permanently lower than reality. Stakeholders make decisions based on incomplete data.',
      'Overcorrection Errors: Late events are added without proper reconciliation. Totals exceed real values due to duplicates or misalignment.',
      'Inconsistent Historical Views: Metrics change retroactively without explanation. Users lose trust in reported numbers.'
    ],
    evaluationCriteria: [
      'Aggregated metrics must converge toward correctness as late data arrives.',
      'Duplicate or replayed events must not inflate results.',
      'Historical consistency must be demonstrable and explainable.',
      'Solutions that assume perfectly ordered or complete data will be penalized.'
    ],
    deliverables: [
      'A small dataset illustrating on-time and late-arriving events.',
      'A working aggregation process showing how metrics evolve over time.',
      'Demonstration of at least one failure scenario being handled correctly.',
      'A brief explanation of known limitations under extreme delays.'
    ]
  },
  {
    id: 'PS-03',
    title: 'Password Reset Abuse Causing Account Lockouts and Support Load',
    domain: 'Cybersecurity',
    difficulty: 'Beginner',
    realWorldContext: 'User-facing web systems commonly provide password reset functionality through email or SMS-based flows. These systems are used daily by real users who forget credentials or rotate passwords. At the same time, automated scripts and low-effort attackers frequently trigger password reset requests against many accounts, sometimes repeatedly, without attempting to complete the reset.',
    coreProblem: 'Password reset mechanisms often lack effective controls to distinguish legitimate recovery attempts from abusive or automated triggering. This leads to repeated reset emails or messages being sent, causing user confusion, perceived account compromise, inbox flooding, and unnecessary support tickets. Existing implementations frequently rely on simplistic rate limits or static thresholds that do not reliably prevent abuse while preserving legitimate access.',
    constraints: [
      'The system cannot rely on knowing whether a user account exists or not during reset initiation.',
      'Requests may originate from shared IPs, NATs, or mobile networks.',
      'Legitimate users may retry multiple times due to delayed email delivery.',
      'The reset flow must remain accessible without requiring prior authentication.',
      'User-facing messages must not leak security-sensitive information.'
    ],
    failureScenarios: [
      'User Lockout Perception: A user receives dozens of reset messages they did not request. They assume their account is compromised and stop using the service.',
      'Support Overload: Large volumes of users contact support after reset spam incidents. Manual handling delays resolution and increases operational cost.',
      'Attacker Signal Amplification: Attackers use reset behaviour to infer account existence indirectly. This information is reused for further attacks.'
    ],
    evaluationCriteria: [
      'Legitimate password reset attempts must remain reliably possible.',
      'Abusive triggering patterns must be measurably reduced.',
      'User-facing behaviour must not reveal account existence.',
      'Naive per-IP or per-minute blocking without consideration of edge cases will be penalized.'
    ],
    deliverables: [
      'A demonstrable password reset request flow with abuse handling.',
      'Evidence showing reduction of repeated or automated triggering.',
      'Clear demonstration of at least one abuse scenario being mitigated.',
      'Brief documentation of remaining risks and trade-offs.'
    ]
  },
  {
    id: 'PS-04',
    title: 'Missed Delivery of Critical Public Service Notifications to Intended Recipients',
    domain: 'Social Impact & Sustainability',
    difficulty: 'Beginner',
    realWorldContext: 'Local administrations, utilities, and community organizations regularly send critical notifications to residents, such as service disruptions, schedule changes, or safety advisories. These messages are intended for specific groups based on location, eligibility, or enrolment status. In practice, notifications are sent daily or weekly, and failures frequently occur where intended recipients do not receive important information in time.',
    coreProblem: 'Notification systems often fail to reliably determine who should receive a message and whether delivery actually occurred. As a result, critical information does not reach vulnerable or affected users, while others receive irrelevant or duplicate messages. Existing approaches rely on static lists or manual targeting that cannot adapt to incomplete or outdated recipient data.',
    constraints: [
      'Recipient data may be incomplete, outdated, or inconsistently formatted.',
      'Users may change contact details without timely updates.',
      'Message delivery confirmation is not guaranteed or uniformly available.',
      'The system must operate under limited administrative oversight.',
      'Notifications may need to be sent within strict time windows.'
    ],
    failureScenarios: [
      'Unreached At-Risk Users: A user affected by a service change does not receive the notification. They miss essential services or safety instructions.',
      'Over-Notification: Users receive messages unrelated to their situation. Trust erodes and future messages are ignored.',
      'False Delivery Assumptions: A message is marked as sent but not actually received. Administrators incorrectly assume successful outreach.'
    ],
    evaluationCriteria: [
      'The system must demonstrate improved alignment between intended and actual recipients.',
      'Missed or failed deliveries must be detectable rather than silent.',
      'Handling of incomplete or stale data must be explicit and observable.',
      'Approaches that assume perfect recipient records will be penalized.'
    ],
    deliverables: [
      'A small representative dataset of recipients and notifications.',
      'A working demonstration showing how recipients are selected and tracked.',
      'Evidence of at least one failure scenario being detected or reduced.',
      'Brief documentation of known limitations and assumptions.'
    ]
  },
  {
    id: 'PS-05',
    title: 'Stale Client-Side State Causing Incorrect Actions After Partial Backend Failures',
    domain: 'Web Development',
    difficulty: 'Intermediate',
    realWorldContext: 'Interactive web applications used for operations such as approvals, inventory updates, or request handling rely heavily on client-side state. These systems are used daily by staff performing sequences of actions across multiple screens. Backend services in such environments experience partial failures, slow responses, or timeouts multiple times per day without fully going offline.',
    coreProblem: 'When backend requests partially fail or time out, client-side state is often left inconsistent with the actual system state. Users continue interacting based on stale or incorrect UI data, leading to repeated actions, conflicting updates, or unintended overwrites. Existing implementations typically assume request success or failure is immediately and cleanly known, which does not hold under real operational conditions.',
    constraints: [
      'Backend responses may be delayed, duplicated, or never arrive.',
      'The client cannot assume idempotency of user-triggered actions.',
      'Users may navigate away and return before a request outcome is known.',
      'Full page reloads are not acceptable due to workflow disruption.',
      'The system must support concurrent actions by multiple users on the same data.'
    ],
    failureScenarios: [
      'False Success Assumption: The UI updates optimistically after an action. The backend request fails silently. Users act on data that was never actually updated.',
      'Duplicate Actions: A user retries an action after a timeout. The backend processes both attempts. The system ends in an unintended state.',
      'Conflicting Edits: Two users act on the same item with stale views. Later updates overwrite earlier valid changes without warning.'
    ],
    evaluationCriteria: [
      'The client must not present unverified state as final.',
      'Inconsistencies between UI and backend state must be detectable.',
      'User actions taken under uncertainty must be constrained or reversible.',
      'Solutions that rely on assuming reliable network or immediate responses will be penalized.'
    ],
    deliverables: [
      'A minimal interactive web interface with simulated backend instability.',
      'Demonstration of how stale state is detected or mitigated.',
      'Evidence showing prevention or handling of at least one failure scenario.',
      'Short explanation of trade-offs made under uncertainty.'
    ]
  },
  {
    id: 'PS-06',
    title: 'Model Output Drift Causing Silent Degradation in Automated Decision Systems',
    domain: 'AI & ML',
    difficulty: 'Intermediate',
    realWorldContext: 'Automated decision systems are used to classify, rank, or flag items such as requests, messages, or transactions. These systems operate continuously, often retraining infrequently while consuming live data streams. In real deployments, the characteristics of incoming data shift gradually due to changes in user behaviour, external conditions, or upstream system updates. This occurs over weeks or months without explicit notice.',
    coreProblem: 'Machine learning systems often continue producing outputs without any reliable indication that their behaviour has meaningfully changed. As data distributions drift, predictions become less accurate or biased, yet the system provides no clear signal that performance has degraded. Existing monitoring commonly relies on static validation metrics or manual review, which fail to detect gradual, silent degradation in time.',
    constraints: [
      'Ground truth labels are delayed, incomplete, or unavailable for most live data.',
      'Historical training data cannot be assumed representative of current inputs.',
      'Manual review capacity is limited and sporadic.',
      'The system must continue operating even under uncertain model quality.',
      'Input features may change subtly without explicit versioning.'
    ],
    failureScenarios: [
      'Gradual Accuracy Loss: Predictions slowly deviate from reality. No alarms trigger because outputs still appear reasonable.',
      'Localized Bias Emergence: Performance degrades for a specific subset of inputs. Aggregate metrics hide the issue.',
      'Delayed Detection: Issues are discovered only after user complaints or audits. Corrective action is costly and reactive.'
    ],
    evaluationCriteria: [
      'The system must provide evidence of detecting meaningful behavioral change.',
      'Detection must function without relying on immediate ground truth.',
      'Trade-offs between sensitivity and false alarms must be explicit.',
      'Approaches that assume stable data distributions will be penalized.'
    ],
    deliverables: [
      'A representative dataset showing changing input characteristics over time.',
      'A demonstrable mechanism highlighting model behavior changes.',
      'Evidence of at least one drift scenario being surfaced.',
      'Brief documentation of known blind spots and assumptions.'
    ]
  },
  {
    id: 'PS-07',
    title: 'Privilege Creep Causing Unintended Access in Role-Based Web Systems',
    domain: 'Cybersecurity',
    difficulty: 'Intermediate',
    realWorldContext: 'Role-based access control is widely used in internal tools, SaaS dashboards, and administrative portals. Users frequently change roles due to promotions, temporary assignments, or project rotations. In real organizations, role updates happen weekly or monthly, while access permissions accumulate over time across multiple systems.',
    coreProblem: 'Access control systems often fail to reliably revoke permissions when user roles change. As a result, users retain access they no longer require, sometimes without visibility to administrators or the users themselves. Existing approaches focus on granting permissions correctly but provide weak guarantees around timely and complete revocation.',
    constraints: [
      'Role changes may be partial, temporary, or ambiguous.',
      'Historical permissions cannot be assumed to be clean or minimal.',
      'Administrators may lack a complete view of effective user access.',
      'Permission checks must not significantly degrade request latency.',
      'The system must function without manual audits for every role change.'
    ],
    failureScenarios: [
      'Silent Over-Permission: A user changes teams but retains prior access. Sensitive data is exposed without triggering alerts.',
      'Accumulated Risk Over Time: Multiple small role changes stack permissions. No single change appears dangerous, but the end state is.',
      'Inconsistent Enforcement: Some parts of the system enforce updated roles. Others rely on cached or outdated permission mappings.'
    ],
    evaluationCriteria: [
      'Effective permissions must accurately reflect current roles.',
      'Excess permissions must be detectable and explainable.',
      'Role transitions must not temporarily grant broader access than intended.',
      'Solutions that assume static roles or manual cleanup will be penalized.'
    ],
    deliverables: [
      'A minimal system demonstrating role assignment and access checks.',
      'Evidence showing detection or prevention of permission accumulation.',
      'Demonstration of at least one role-change failure scenario being handled.',
      'Short explanation of trade-offs between strictness and usability.'
    ]
  },
  {
    id: 'PS-08',
    title: 'Inconsistent Analytics Results Due to Mixed Granularity Data Sources',
    domain: 'Data & Analytics',
    difficulty: 'Intermediate',
    realWorldContext: 'Operational and product teams rely on analytics dashboards built from multiple data sources, such as event logs, periodic summaries, and manual adjustments. These data sources are updated at different intervals—some in real time, others hourly or daily. This situation occurs continuously in organizations where analytics are assembled incrementally rather than through a single unified pipeline.',
    coreProblem: 'Analytics systems frequently combine data sources with different time granularities and update cadences without explicitly reconciling them. As a result, dashboards present internally inconsistent numbers where totals, subtotals, and trends do not align. Existing implementations often mask these inconsistencies through implicit joins or overwrites, making it unclear which numbers are trustworthy.',
    constraints: [
      'Data sources cannot be forced to align to a single update schedule.',
      'Some data is only available in aggregated form.',
      'Late corrections may apply to historical periods.',
      'The system must present analytics continuously, not only after full reconciliation.',
      'Users expect stable numbers within a reporting session.'
    ],
    failureScenarios: [
      'Conflicting Totals: A daily total does not equal the sum of hourly breakdowns. Users cannot determine which value is correct.',
      'Temporal Flicker: Metrics change when a slower data source updates. Users observe unexplained shifts in historical data.',
      'Hidden Data Gaps: Missing periods are silently filled or ignored. Decisions are made on incomplete information.'
    ],
    evaluationCriteria: [
      'Internal consistency between related metrics must be demonstrable.',
      'The system must clearly expose when data is provisional or incomplete.',
      'Handling of late or partial updates must be observable.',
      'Solutions that silently merge incompatible data will be penalized.'
    ],
    deliverables: [
      'A small set of datasets with differing granularities and update times.',
      'A working analytics view showing how inconsistencies are handled.',
      'Demonstration of at least one failure scenario being surfaced.',
      'Brief documentation of assumptions and remaining limitations.'
    ]
  },
  {
    id: 'PS-09',
    title: 'Undetected Training–Serving Skew Causing Invalid Model Decisions in Production',
    domain: 'AI & ML',
    difficulty: 'Advanced',
    realWorldContext: 'Production ML systems are trained offline and then deployed to make real-time or batch decisions affecting users or operations. These systems ingest features produced by upstream services that evolve independently over time. In real deployments, feature definitions, preprocessing logic, or data sources change gradually or silently, occurring sporadically across weeks or months.',
    coreProblem: 'Machine learning models often operate with different feature semantics during training and serving without explicit detection. This training–serving skew leads to systematically incorrect predictions while models continue to produce confident outputs. Existing approaches rely on manual checks, documentation discipline, or periodic retraining, none of which reliably detect skew once systems are live.',
    constraints: [
      'Feature pipelines for training and serving are not guaranteed to share code or execution paths.',
      'Ground truth for live predictions is delayed or incomplete.',
      'Feature values may remain syntactically valid while being semantically wrong.',
      'Upstream data producers may change behavior without coordination.',
      'The system must continue serving predictions even when skew is suspected.'
    ],
    failureScenarios: [
      'Silent Semantic Drift: A feature changes meaning but keeps the same name and type. Model behavior degrades without obvious errors.',
      'Partial Skew: Only a subset of features diverges. Aggregate performance metrics mask the issue.',
      'Delayed Discovery: Skew is detected only after audits or downstream failures. Reconstructing the cause becomes difficult or impossible.'
    ],
    evaluationCriteria: [
      'The system must surface evidence of divergence between training and serving data.',
      'Detection must not depend on immediate access to labels.',
      'False alarms and missed detections must be explicitly trade-offed.',
      'Solutions assuming shared pipelines or perfect coordination will be penalized.'
    ],
    deliverables: [
      'A controlled dataset illustrating aligned and misaligned feature behavior.',
      'A demonstrable mechanism highlighting skew under at least one failure scenario.',
      'Clear evidence showing how skew is detected while predictions continue.',
      'Brief documentation of assumptions and unavoidable blind spots.'
    ]
  },
  {
    id: 'PS-10',
    title: 'Credential Exposure Through Over-Permissive Client-Side Error Logging',
    domain: 'Cybersecurity',
    difficulty: 'Advanced',
    realWorldContext: 'Web and API-based systems commonly collect client-side error logs to diagnose failures experienced by users. These logs are generated continuously across production environments and reviewed by engineers and support teams. In real organizations, logging configurations evolve rapidly during incident response or feature rollout, often without systematic review.',
    coreProblem: 'Client-side error logging frequently captures and transmits sensitive data such as authentication tokens, session identifiers, or personal information embedded in requests. This data becomes accessible to internal teams, third-party tooling, or unintended recipients, creating a latent security exposure. Existing implementations focus on log completeness for debugging, with insufficient controls to prevent sensitive data leakage under failure conditions.',
    constraints: [
      'Error logs are generated automatically during unexpected failures.',
      'Logged data may include raw request or response payloads.',
      'Engineers require enough context to diagnose issues under time pressure.',
      'Sensitive fields are not consistently labeled or structured.',
      'Logging behavior cannot be fully disabled without losing operational visibility.'
    ],
    failureScenarios: [
      'Token Leakage: Authentication tokens are logged during API failures. Logs are accessed by users or systems not authorized to see them.',
      'Persistent Exposure: Sensitive logs are retained longer than intended. Exposure remains unnoticed until an audit or incident.',
      'Over-Reaction: Aggressive filtering removes critical debugging context. Engineers are unable to diagnose real failures in time.'
    ],
    evaluationCriteria: [
      'Sensitive data must be demonstrably prevented from appearing in logs.',
      'Debugging usefulness under failure conditions must be preserved.',
      'Handling of unknown or malformed fields must be explicit.',
      'Approaches relying on manual log review or naming conventions alone will be penalized.'
    ],
    deliverables: [
      'A simulated client-side logging setup with representative error cases.',
      'Evidence showing prevention of sensitive data exposure.',
      'Demonstration of at least one failure scenario being handled correctly.',
      'Short documentation describing trade-offs and remaining risks.'
    ]
  },
  {
    id: 'PS-11',
    title: 'Irreversible Data Corruption from Concurrent Writes in Shared Analytical Tables',
    domain: 'Data & Analytics',
    difficulty: 'Advanced',
    realWorldContext: 'Shared analytical tables are commonly updated by multiple automated jobs and ad-hoc processes, such as scheduled reports, backfills, and manual corrections. These updates occur daily in data warehouses and reporting systems used by business and operational teams. Coordination between jobs is often informal, and execution overlaps are common during peak processing windows.',
    coreProblem: 'Analytical data stores frequently allow concurrent writes without sufficient safeguards against overlapping updates. When multiple processes write to the same logical data ranges, partial overwrites, lost updates, or silent corruption occur. Existing practices often rely on timing assumptions or manual sequencing, which break under retries, delays, or operational pressure.',
    constraints: [
      'Multiple writers may operate independently and cannot be centrally orchestrated.',
      'Write operations may partially succeed before failing.',
      'Historical data corrections must remain possible.',
      'Full table rebuilds are too costly to perform routinely.',
      'Detection must occur without relying on downstream user complaints.'
    ],
    failureScenarios: [
      'Lost Updates: One job overwrites changes made by another. Corrections silently disappear from reports.',
      'Partial Corruption: A write fails midway, leaving mixed old and new data. No immediate error is visible in aggregates.',
      'Delayed Discovery: Corruption is detected weeks later during reconciliation. Root cause attribution becomes impractical.'
    ],
    evaluationCriteria: [
      'The system must detect or prevent overlapping writes to the same data ranges.',
      'Partial or failed writes must be identifiable after execution.',
      'Historical integrity must be demonstrable.',
      'Solutions assuming single-writer execution will be penalized.'
    ],
    deliverables: [
      'A representative dataset with concurrent update scenarios.',
      'Demonstration of at least one corruption scenario being prevented or detected.',
      'Evidence showing how partial failures are handled.',
      'Brief explanation of trade-offs and remaining edge cases.'
    ]
  },
  {
    id: 'PS-12',
    title: 'Eligibility Misclassification Causing Denial of Time-Critical Social Benefits',
    domain: 'Social Impact & Sustainability',
    difficulty: 'Advanced',
    realWorldContext: 'Public assistance programs and community services rely on eligibility rules to determine access to benefits such as food support, housing aid, fee waivers, or emergency relief. Eligibility is assessed repeatedly as applicants’ circumstances change due to income fluctuation, employment shifts, or household changes. These assessments occur continuously in real systems, especially during periods of economic stress or emergencies.',
    coreProblem: 'Eligibility determination systems frequently misclassify applicants due to stale, incomplete, or conflicting input data. As a result, eligible individuals are denied benefits, or ineligible individuals receive them, without timely detection. Existing processes rely heavily on periodic reviews or manual appeals, which are too slow to prevent real harm when decisions are time-sensitive.',
    constraints: [
      'Applicant data may be self-reported and partially unverifiable at decision time.',
      'External data sources update asynchronously and may contradict each other.',
      'Eligibility rules are fixed and cannot be simplified or relaxed.',
      'Manual review capacity is limited and delayed.',
      'Decisions must be issued within strict time windows.'
    ],
    failureScenarios: [
      'False Ineligibility: An applicant’s data is temporarily inconsistent. Benefits are denied during a critical period.',
      'Stale Eligibility: A previously eligible applicant’s status changes. Benefits continue incorrectly, consuming limited resources.',
      'Untraceable Decisions: An eligibility outcome cannot be reconstructed later. Appeals and audits fail due to missing decision context.'
    ],
    evaluationCriteria: [
      'The system must surface uncertainty or conflict in eligibility inputs.',
      'Incorrect decisions must be detectable after issuance.',
      'Time-to-decision constraints must be respected.',
      'Approaches assuming complete or perfectly verified data will be penalized.'
    ],
    deliverables: [
      'A representative dataset with changing applicant conditions.',
      'Demonstration of at least one misclassification scenario being detected or flagged.',
      'Evidence showing how decisions and their inputs are traceable.',
      'Brief documentation of known limitations under extreme data inconsistency.'
    ]
  },
  {
    id: 'PS-13',
    title: 'Adversarial Input Causing Silent Policy Evasion in Automated Content Moderation',
    domain: 'AI & ML',
    difficulty: 'Extreme',
    realWorldContext: 'Automated content moderation systems are used to review text submissions such as comments, reports, or messages at scale. These systems operate continuously in public-facing platforms where users submit content in real time. Adversarial users actively test moderation boundaries daily, iteratively adapting inputs to bypass enforcement while remaining human-readable.',
    coreProblem: 'Content moderation systems fail to reliably detect policy-violating content when adversarial users intentionally manipulate language, structure, or encoding. These evasions do not break system inputs and often appear benign under standard processing, allowing harmful content to pass undetected. Existing approaches rely heavily on static patterns, historical training data, or confidence thresholds that lag behind adversarial adaptation.',
    constraints: [
      'Inputs must be processed in near real time with strict latency limits.',
      'Ground truth for adversarial content is sparse and delayed.',
      'Policy definitions are fixed and cannot be reinterpreted dynamically.',
      'False positives carry high user trust and appeal costs.',
      'Attackers actively probe the system based on observed outcomes.'
    ],
    failureScenarios: [
      'Semantic Obfuscation: Harmful meaning is encoded through altered spelling or phrasing. The system fails to recognize intent.',
      'Adaptive Evasion: Attackers modify inputs based on previous rejections. Detection effectiveness degrades over time.',
      'Confidence Masking: Outputs remain high-confidence despite incorrect classification. No internal signals indicate elevated risk.'
    ],
    evaluationCriteria: [
      'The system must surface indicators of adversarial uncertainty or instability.',
      'Detection effectiveness under adaptive input changes must be demonstrable.',
      'Trade-offs between false positives and missed violations must be explicit.',
      'Solutions assuming static attacker behaviour will be penalized.'
    ],
    deliverables: [
      'A dataset containing benign, policy-violating, and adversarial modified inputs.',
      'Demonstration of at least one evasion scenario being surfaced or constrained.',
      'Evidence showing system behaviour changes under adaptive probing.',
      'Brief documentation of residual risks and blind spots.'
    ]
  },
  {
    id: 'PS-14',
    title: 'Coordinated Low-Rate Attacks Evading Detection in Distributed Authentication Systems',
    domain: 'Cybersecurity',
    difficulty: 'Extreme',
    realWorldContext: 'Authentication systems protect access to user accounts across web and mobile services. These systems operate continuously and handle large volumes of login attempts from geographically and network-diverse sources. In real environments, attackers routinely distribute credential-stuffing or password-guessing attempts across many IPs, devices, or time windows to avoid triggering conventional defences.',
    coreProblem: 'Authentication defences often fail to detect malicious activity when attackers intentionally keep request rates below traditional thresholds. Each individual login attempt appears legitimate, yet the aggregate behaviour represents a coordinated attack. Existing protections rely heavily on per-IP limits, short time windows, or static rules that cannot reliably identify slow, distributed adversarial patterns.',
    constraints: [
      'Login attempts must be processed with minimal added latency.',
      'Legitimate users may also exhibit irregular login behaviour.',
      'Source identifiers such as IP addresses or devices are unreliable and mutable.',
      'The system cannot block large populations pre-emptively.',
      'Attackers adapt behaviour based on observed blocking or challenges.'
    ],
    failureScenarios: [
      'Silent Credential Stuffing: Attack attempts are spread thinly over time and sources. Compromises occur without any rate limit being triggered.',
      'False Positives on Legitimate Users: Legitimate users with unstable connectivity are flagged. Access is denied without clear justification.',
      'Delayed Detection: Attack patterns are recognized only after accounts are compromised. Damage control becomes reactive and costly.'
    ],
    evaluationCriteria: [
      'The system must surface coordinated behaviour that is not visible at single-request level.',
      'Legitimate low-volume users must remain able to authenticate.',
      'Detection logic must remain effective as attackers adapt timing and sources.',
      'Approaches relying solely on fixed thresholds or static identifiers will be penalized.'
    ],
    deliverables: [
      'A representative stream of authentication attempts including benign and coordinated attack patterns.',
      'Demonstration of at least one low-rate attack scenario being detected or constrained.',
      'Evidence showing system behaviour under adaptive attacker adjustments.',
      'Brief documentation of detection limits and unavoidable trade-offs.'
    ]
  },
  {
    id: 'PS-15',
    title: 'Strategic Misallocation of Emergency Resources Due to Conflicting Real-Time Signals',
    domain: 'Social Impact & Sustainability',
    difficulty: 'Extreme',
    realWorldContext: 'Emergency response teams allocate limited resources such as relief supplies, personnel, or services during disasters, public health crises, or infrastructure failures. Decisions are made continuously using live inputs from field reports, sensors, and public submissions. In real events, these signals arrive simultaneously, conflict with each other, and vary widely in reliability.',
    coreProblem: 'Emergency coordination systems fail to reconcile conflicting real-time signals into decisions that reflect actual on-ground conditions. As a result, resources are sent to lower-priority areas while higher-need locations are under-served. Existing processes rely on manual judgment or simplistic prioritization that cannot consistently handle ambiguity and signal conflict under time pressure.',
    constraints: [
      'Resource availability is strictly limited and cannot be over-allocated.',
      'Incoming signals differ in timeliness, reliability, and completeness.',
      'Ground truth verification is delayed or impossible during active response.',
      'Decisions must be made within minutes, not hours.',
      'Reallocation has real costs and cannot be done repeatedly.'
    ],
    failureScenarios: [
      'Signal Dominance Bias: High-volume but low-accuracy reports dominate decisions. Critical low-signal areas are ignored.',
      'Stale Priority Lock-In: Early signals anchor decisions. Changing conditions are not reflected in allocations.',
      'Overreaction to Noise: Resources are redirected based on unreliable spikes. Other areas experience preventable shortages.'
    ],
    evaluationCriteria: [
      'The system must make allocation decisions that reflect signal reliability and conflict.',
      'Decision rationale must be inspectable after the fact.',
      'The impact of delayed or noisy inputs must be explicitly handled.',
      'Approaches assuming clean, authoritative signals will be penalized.'
    ],
    deliverables: [
      'A representative dataset of conflicting real-time signals and resource constraints.',
      'Demonstration of at least one misallocation scenario being mitigated. ',
      'Evidence showing how decisions adapt as signals evolve.',
      'Brief documentation of failure modes that remain unresolved.'
    ]
  }
];

export const getProblemStatements = () => mockProblemStatements;

// --- Helper Functions for Data Mapping ---

const mapSqlToTeam = (data: any): Team => {
  const evaluations: Record<string, Evaluation> = {};

  if (data.evaluations && Array.isArray(data.evaluations)) {
    data.evaluations.forEach((ev: any) => {
      evaluations[ev.judge_name] = { presentationScore: ev.score };
    });
  }

  return {
    id: data.id,
    teamName: data.team_name,
    leadName: data.lead_name,
    email: data.lead_email,
    phone: data.lead_phone,
    teamSize: data.team_size,
    members: data.members || [],
    psId: data.ps_id,
    ideaDesc: data.idea_desc,
    pptUrl: data.ppt_url || '#',
    panel: data.panel,
    adminPptScore: data.admin_ppt_score,
    status: data.status as TeamStatus,
    evaluations: evaluations,
    totalScore: data.total_score || 0,
    submissionDate: data.submission_date
  };
};

// --- Service Methods ---

export const getTeams = async (): Promise<Team[]> => {
  const { data, error } = await supabase
    .from('teams')
    .select('*, members(*), evaluations(*)');

  if (error) {
    console.error("Error fetching teams:", error);
    return [];
  }

  return data.map(mapSqlToTeam);
};

export const getTeamById = async (id: string): Promise<Team | undefined> => {
  const { data, error } = await supabase
    .from('teams')
    .select('*, members(*), evaluations(*)')
    .eq('id', id)
    .single();

  if (error || !data) {
    return undefined;
  }

  return mapSqlToTeam(data);
};

export const getTeamByUserEmail = async (email: string): Promise<Team | undefined> => {
  // First check if user is a lead
  const { data: leadData } = await supabase
    .from('teams')
    .select('*, members(*), evaluations(*)')
    .eq('lead_email', email)
    .single();

  if (leadData) return mapSqlToTeam(leadData);

  // Then check if user is a member
  // Note: This requires a 2-step lookup or a join if we want to be efficient, 
  // but for now 2-step is safer with the current schema capabilities.
  const { data: memberData } = await supabase
    .from('members')
    .select('team_id')
    .eq('email', email)
    .single();

  if (memberData && memberData.team_id) {
    return getTeamById(memberData.team_id);
  }

  return undefined;
};

export const createTeam = async (teamData: Omit<Team, 'id' | 'status' | 'evaluations' | 'totalScore' | 'submissionDate' | 'panel'>, file: File | null): Promise<Team> => {

  // 1. Generate ID
  const generateUniqueId = () => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let result = 'SUB-';
    for (let i = 0; i < 6; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  };
  const submissionId = generateUniqueId();

  // 2. Determine PPT URL (File Upload is Mandatory, but we preserve Manual Link if given)
  let finalPptUrl = '';
  const manualLink = teamData.pptUrl;

  // If a file is uploaded, it becomes the primary PPT URL
  if (file) {
    const fileExt = file.name.split('.').pop();
    const fileName = `${submissionId}.${fileExt}`;
    const filePath = `${submissionId}/${fileName}`;

    // Try uploading to 'documents' bucket
    const bucketName = 'documents';
    const { error: uploadError } = await supabase.storage
      .from(bucketName)
      .upload(filePath, file);

    if (uploadError) {
      if (uploadError.message.includes("Bucket not found")) {
        console.error("CRITICAL: The 'documents' bucket does not exist in your Supabase Storage. Please create a public bucket named 'documents'.");
      }
      console.warn("File upload failed:", uploadError.message);
    } else {
      const { data } = supabase.storage.from(bucketName).getPublicUrl(filePath);
      finalPptUrl = data.publicUrl;
    }
  }

  // 3. Prepare Payload
  // If user provided a Manual Link, we append it to the description so it's not lost.
  let finalDesc = teamData.ideaDesc;
  if (manualLink && manualLink.trim() !== '') {
    finalDesc += `\n\n[Additional Link]: ${manualLink}`;
  }

  // 3. Insert Team
  const teamPayload = {
    id: submissionId,
    team_name: teamData.teamName,
    lead_name: teamData.leadName,
    lead_email: teamData.email,
    lead_phone: teamData.phone,
    team_size: teamData.teamSize,
    ps_id: teamData.psId,
    idea_desc: finalDesc,
    ppt_url: finalPptUrl, // Stores the uploaded file link
    status: TeamStatus.SUBMITTED,
    total_score: 0
  };

  const { error: insertError } = await supabase.from('teams').insert(teamPayload);
  if (insertError) throw new Error(insertError.message);

  // 4. Insert Members
  if (teamData.members.length > 0) {
    const membersPayload = teamData.members.map(m => ({
      team_id: submissionId,
      name: m.name,
      email: m.email,
      phone: m.phone
    }));
    const { error: memberError } = await supabase.from('members').insert(membersPayload);
    if (memberError) console.error("Error inserting members:", memberError);
  }

  // Return constructed team object for UI
  return {
    ...teamData,
    id: submissionId,
    status: TeamStatus.SUBMITTED,
    evaluations: {},
    totalScore: 0,
    submissionDate: new Date().toISOString(),
    panel: undefined,
    adminPptScore: undefined,
    pptUrl: finalPptUrl
  };
};

export const updateTeamStatus = async (id: string, status: TeamStatus): Promise<void> => {
  await supabase.from('teams').update({ status }).eq('id', id);
};

export const updateTeamPanel = async (id: string, panel: 'A' | 'B'): Promise<void> => {
  await supabase.from('teams').update({ panel }).eq('id', id);
};

export const deleteTeam = async (id: string): Promise<void> => {
  await supabase.from('teams').delete().eq('id', id);
};

// Helper to calculate total score (re-used logic but fetched fresh)
const calculateTotalScore = (adminScore: number, evaluations: any[]): number => {
  let avgJudgeScore = 0;
  if (evaluations.length > 0) {
    const sumJudgeScores = evaluations.reduce((acc, curr) => acc + curr.score, 0);
    avgJudgeScore = sumJudgeScores / evaluations.length;
  }
  return (adminScore || 0) + avgJudgeScore;
};

// Admin submits PPT Score
export const submitAdminPptScore = async (teamId: string, score: number): Promise<void> => {
  // Update admin score
  await supabase.from('teams').update({ admin_ppt_score: score }).eq('id', teamId);

  // Recalculate Total
  const { data: team } = await supabase.from('teams').select('*, evaluations(*)').eq('id', teamId).single();
  if (team) {
    const newTotal = calculateTotalScore(score, team.evaluations || []);
    await supabase.from('teams').update({ total_score: newTotal }).eq('id', teamId);
  }
};

// Evaluator submits Presentation Score
export const submitEvaluation = async (teamId: string, judgeName: string, presentationScore: number): Promise<void> => {
  // Check if exists
  const { data: existing } = await supabase
    .from('evaluations')
    .select('*')
    .eq('team_id', teamId)
    .eq('judge_name', judgeName)
    .single();

  if (existing) {
    await supabase.from('evaluations').update({ score: presentationScore }).eq('id', existing.id);
  } else {
    await supabase.from('evaluations').insert({
      team_id: teamId,
      judge_name: judgeName,
      score: presentationScore
    });
  }

  // Recalculate Total
  const { data: team } = await supabase.from('teams').select('*, evaluations(*)').eq('id', teamId).single();
  if (team) {
    const newTotal = calculateTotalScore(team.admin_ppt_score, team.evaluations || []);
    await supabase.from('teams').update({ total_score: newTotal }).eq('id', teamId);
  }
};

// --- Auth Logic ---

// Store registered users (Email -> Password) to prevent duplicates and allow mock login
// We prioritize localStorage to persist users across reloads
const getStoredUsers = (): [string, string][] => {
  if (typeof localStorage === 'undefined') return [];
  try {
    const item = localStorage.getItem('mock_users');
    return item ? JSON.parse(item) : [];
  } catch (e) {
    console.error("Failed to load mock users", e);
    return [];
  }
};

const registeredUsers = new Map<string, string>(getStoredUsers());

const saveUsers = () => {
  if (typeof localStorage === 'undefined') return;
  try {
    localStorage.setItem('mock_users', JSON.stringify(Array.from(registeredUsers.entries())));
  } catch (e) {
    console.error("Failed to save mock users", e);
  }
};

interface JudgeInfo {
  name: string;
  panel: 'A' | 'B';
}

const JUDGE_CODES: Record<string, JudgeInfo> = {
  'PRANAY#JUDGE@2026': { name: 'Dr. Pranay Saraf', panel: 'A' },
  'VIBHA#JUDGE@2026': { name: 'Vibha Mam', panel: 'A' },
  'VIBHU#JUDGE@2026': { name: 'Vibhu Mam', panel: 'A' },
  'KETAN#JUDGE@2026': { name: 'Ketan Sir', panel: 'B' },
  'SACHIN#JUDGE@2026': { name: 'Sachin Sir', panel: 'B' }
};

const ADMIN_CODE = 'INNOVEXA2@chairperson#';

export const authenticateUser = (code: string): UserSession | null => {
  if (code === ADMIN_CODE) {
    return { role: UserRole.ADMIN, name: 'Chairperson' };
  }

  if (JUDGE_CODES[code]) {
    return {
      role: UserRole.EVALUATOR,
      name: JUDGE_CODES[code].name,
      judgeId: code,
      panel: JUDGE_CODES[code].panel
    };
  }

  return null;
};

// Student Auth - Using Supabase Auth
export const registerStudent = async (name: string, email: string, pass: string): Promise<UserSession> => {
  try {
    // Basic validation
    if (!name || !email || !pass) {
      throw new Error("All fields are required");
    }

    if (pass.length < 8) {
      throw new Error("Password must be at least 8 characters");
    }

    // Strong password validation: uppercase, lowercase, number, special char
    const strongPasswordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
    if (!strongPasswordRegex.test(pass)) {
      throw new Error("Password must contain uppercase, lowercase, number, and special character (@$!%*?&)");
    }

    // Check if email already registered (prevent duplicates)
    const normalizedEmail = email.toLowerCase();
    if (registeredUsers.has(normalizedEmail)) {
      throw new Error("This email is already registered. Please log in instead.");
    }

    // Store implicitly first to ensure fallback works even if Supabase call crashes
    // Note: In real prod, this is backwards, but for this demo robustness, it's safer.
    // However, if Supabase succeeds, we are good. If it fails, we fall back.

    // Let's try Supabase first
    const { data, error } = await supabase.auth.signUp({
      email,
      password: pass,
      options: {
        data: { full_name: name, role: UserRole.STUDENT }
      }
    });

    if (error) {
      // If rate limited or other specific error, fallback to mock session
      if (error.message.includes("rate limit") || error.status === 429 || error.status === 400 || error.message.includes("security purposes")) {
        console.warn("Supabase auth error/limit. Falling back to mock session.");
        registeredUsers.set(normalizedEmail, pass);
        saveUsers(); // PERSIST
        return {
          role: UserRole.STUDENT,
          name: name,
          email: email
        };
      }
      if (error.message.includes("already registered")) {
        throw new Error("This email is already registered. Please log in instead.");
      }
      throw new Error(error.message || "Registration failed");
    }

    // Add email to registered map (store password too, just in case Supabase login fails later heavily)
    registeredUsers.set(normalizedEmail, pass);
    saveUsers(); // PERSIST

    return {
      role: UserRole.STUDENT,
      name: name,
      email: email
    };
  } catch (err: any) {
    // Fallback for demo
    if (err.message?.includes("rate limit") || err.message?.includes("security purposes")) {
      console.warn("Supabase auth error. Falling back to mock session.", err);
      registeredUsers.set(email.toLowerCase(), pass);
      saveUsers(); // PERSIST
      return {
        role: UserRole.STUDENT,
        name: name,
        email: email
      };
    }
    throw new Error(err.message || "Registration failed. Please try again.");
  }
};

export const loginStudent = async (email: string, pass: string): Promise<UserSession> => {
  try {
    // Basic validation
    if (!email || !pass) {
      throw new Error("Email and password are required");
    }

    const normalizedEmail = email.toLowerCase();

    // 1. Try Supabase Login
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password: pass
    });

    if (error) {
      // 2. If Supabase fails (rate limit OR invalid login), check our in-memory mock store
      if (registeredUsers.has(normalizedEmail)) {
        const storedPass = registeredUsers.get(normalizedEmail);
        if (storedPass === pass) {
          console.warn("Supabase login failed, but found in mock store. Logging in.");
          const mockName = email.split('@')[0];
          return {
            role: UserRole.STUDENT,
            name: mockName,
            email: email
          };
        }
      }

      if (error.message.includes("rate limit") || error.status === 429) {
        // If we don't have it in memory but it's a rate limit, maybe we let them in for demo? 
        // Better to fail if password doesn't match anything.
        // But preserving original behavior:
        if (registeredUsers.has(normalizedEmail)) {
          // Already handled above
        }
      }

      if (error.message.includes("Invalid login") || error.message.includes("invalid") || error.status === 400) {
        throw new Error("Invalid email or password. Please try again.");
      }
      throw new Error(error.message || "Login failed");
    }

    return {
      role: UserRole.STUDENT,
      name: data.user?.user_metadata?.full_name || 'Student',
      email: email
    };
  } catch (err: any) {
    // Check mock store one last time if it was a throw
    const normalizedEmail = email.toLowerCase();
    if (registeredUsers.has(normalizedEmail)) {
      const storedPass = registeredUsers.get(normalizedEmail);
      if (storedPass === pass) {
        const mockName = email.split('@')[0];
        return {
          role: UserRole.STUDENT,
          name: mockName,
          email: email
        };
      }
    }
    throw new Error(err.message || "Login failed. Please check your credentials.");
  }
};

// Handle Google OAuth Login/Registration
// Handle Google OAuth Login/Registration
export const loginWithGoogle = async (idToken: string): Promise<UserSession> => {
  try {
    // Exchange Google ID Token for Supabase Session
    const { data, error } = await supabase.auth.signInWithIdToken({
      provider: 'google',
      token: idToken,
    });

    if (error) {
      console.error("Supabase Google Auth Error:", error);
      throw new Error(error.message || "Google Login verification failed");
    }

    const { user } = data;
    const email = user?.email;
    const name = user?.user_metadata?.full_name || user?.user_metadata?.name || email?.split('@')[0] || "Google User";

    if (!email) {
      throw new Error("No email found in Google profile");
    }

    // Add to local mock store to persist session expectation if needed
    // (Though for OAuth, Supabase manages the session)

    return {
      role: UserRole.STUDENT,
      name: name,
      email: email
    };
  } catch (err: any) {
    throw new Error(err.message || "Google Login failed");
  }
};
